name: dbt Daily Production Run

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  production_pipeline:
    runs-on: ubuntu-latest

    env:
      DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
      DBT_SNOWFLAKE_USER: ${{ secrets.DBT_SNOWFLAKE_USER }}
      DBT_SNOWFLAKE_PASSWORD: ${{ secrets.DBT_SNOWFLAKE_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run SCD Type 2 Snapshots
        run: |
          dbt snapshot --project-dir analytics --profiles-dir analytics --target prod

      - name: Run Incremental Models & Tests
        run: |
          dbt build --project-dir analytics --profiles-dir analytics --target prod
